const fs = require('fs');
const path = require('path');

const sourcePath = path.resolve(__dirname, 'sensors-extracted.json');
const sensors = JSON.parse(fs.readFileSync(sourcePath, 'utf8'));

const groups = [
  { id: 'ssn', name: 'Space Surveillance Network Sensors', badge: 'COALITION', sensorIds: ['EGLAFB','KWAJSPF','GEODDSDGC','GEODDSMAU','GEODDSSOC','KWAJALT','KWAJMMW','KWAJALC','KWAJTDX','MITMIL','RAFASC','GLBII','HOLCBAND','HOLSST'] },
  { id: 'mw', name: 'US Missile Warning Sensors', badge: 'NORAD', sensorIds: ['BLEAFB','CODSFS','CAVSFS','CLRSFS','RAFFYL','PITSB'] },
  { id: 'md', name: 'US Missile Defense Agency Sensors', badge: 'MDA', sensorIds: ['LRDR','COBRADANE','HARTPY','QTRTPY','KURTPY','SHATPY','KCSTPY','SBXRDR'] },
  { id: 'owl-net', name: 'OWL-Net Sensors', badge: 'OWL-Net', sensorIds: ['OWLKorea','OWLMongolia','OWLMorocco','OWLIsrael','OWLUSA'] },
  { id: 'leolabs', name: 'LeoLabs Sensors', badge: 'LEOLABS', sensorIds: ['LEOCRSR','LEOAZORES','LEOKSR','LEOPFISR','LEOMSR'] },
  { id: 'esoc', name: 'European Space Operations Centre Sensors', badge: 'ESA', sensorIds: ['GRV','TIR','GES','NRC','PDM','TRO','SDT','ZimLAT','ZimSMART','Tromso','Kiruna','Sodankyla','Svalbard'] },
  { id: 'rus', name: 'Russian Sensors', badge: 'RUSSIA', sensorIds: ['OLED','OLEV','PEC','MISD','MISV','LEKV','ARMV','KALV','BARV','YENV','ORSV','STO','NAK'] },
  { id: 'prc', name: 'Chinese Sensors', badge: 'CHINA', sensorIds: ['SHD','HEI','ZHE','XIN','PMO'] },
  { id: 'other', name: 'Other Sensors', badge: 'OTHER', sensorIds: ['ROC','MLS','PO','LSO','MAY'] },
];

const typeMap = {
  PHASED_ARRAY_RADAR: 'Phased Array Radar',
  MECHANICAL: 'Mechanical Radar',
  OPTICAL: 'Optical Telescope',
  LASER: 'Laser Sensor',
  OBSERVER: 'Optical Observer'
};

function toMeters(km) {
  if (km === null || km === undefined) return null;
  return Number((km * 1000).toFixed(2));
}

function sanitize(value) {
  if (value === undefined) return null;
  return value;
}

const sensorEntries = Object.entries(sensors).map(([id, data]) => {
  const name = data.uiName || data.name || id;
  const shortName = data.shortName || null;
  const typeKey = data.type || null;
  const altitude = toMeters(data.alt ?? null);
  const base = {
    id,
    name,
    shortName,
    system: data.system || null,
    country: data.country || null,
    operator: data.operator || null,
    type: typeKey && typeMap[typeKey] ? typeMap[typeKey] : (typeKey ? typeKey.replace(/_/g, ' ').toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase()) : null),
    latitude: data.lat ?? null,
    longitude: data.lon ?? null,
    altitudeMeters: altitude,
    minAzimuth: sanitize(data.minAz ?? data.azMin),
    maxAzimuth: sanitize(data.maxAz ?? data.azMax),
    minElevation: sanitize(data.minEl ?? data.elMin),
    maxElevation: sanitize(data.maxEl ?? data.elMax),
    minRangeKm: sanitize(data.minRng ?? data.rngMin),
    maxRangeKm: sanitize(data.maxRng ?? data.rngMax),
    frequencyBand: data.freqBand || null,
    notes: data.description || null,
  };
  return base;
}).sort((a, b) => a.id.localeCompare(b.id));

function formatValue(value) {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'string') {
    return `\`${value.replace(/`/g, '\\`')}\``;
  }
  return String(value);
}

const sensorLines = sensorEntries.map((entry) => {
  const fields = [
    `id: \`${entry.id}\``,
    `name: ${formatValue(entry.name)}`,
    `shortName: ${formatValue(entry.shortName)}`,
    `system: ${formatValue(entry.system)}`,
    `country: ${formatValue(entry.country)}`,
    `operator: ${formatValue(entry.operator)}`,
    `type: ${formatValue(entry.type)}`,
    `latitude: ${entry.latitude ?? 'null'}`,
    `longitude: ${entry.longitude ?? 'null'}`,
    `altitudeMeters: ${entry.altitudeMeters ?? 'null'}`,
    `minAzimuth: ${entry.minAzimuth ?? 'null'}`,
    `maxAzimuth: ${entry.maxAzimuth ?? 'null'}`,
    `minElevation: ${entry.minElevation ?? 'null'}`,
    `maxElevation: ${entry.maxElevation ?? 'null'}`,
    `minRangeKm: ${entry.minRangeKm ?? 'null'}`,
    `maxRangeKm: ${entry.maxRangeKm ?? 'null'}`,
    `frequencyBand: ${formatValue(entry.frequencyBand)}`,
    `notes: ${formatValue(entry.notes)}`,
  ];
  return `  { ${fields.join(', ')} }`;
}).join(',\n');

const groupLines = groups.map((group) => {
  const sensorsList = group.sensorIds.map((id) => `\`${id}\``).join(', ');
  return `  { id: \`${group.id}\`, name: \`${group.name}\`, badge: \`${group.badge}\`, sensorIds: [${sensorsList}] }`;
}).join(',\n');

const output = `// Auto-generated by scripts/buildSensorData.cjs\n\nexport interface SensorDefinition {\n  id: string;\n  name: string;\n  shortName: string | null;\n  system: string | null;\n  country: string | null;\n  operator: string | null;\n  type: string | null;\n  latitude: number | null;\n  longitude: number | null;\n  altitudeMeters: number | null;\n  minAzimuth: number | null;\n  maxAzimuth: number | null;\n  minElevation: number | null;\n  maxElevation: number | null;\n  minRangeKm: number | null;\n  maxRangeKm: number | null;\n  frequencyBand: string | null;\n  notes: string | null;\n}\n\nexport interface SensorGroupDefinition {\n  id: string;\n  name: string;\n  badge: string;\n  sensorIds: string[];\n}\n\nexport const SENSOR_DEFINITIONS: SensorDefinition[] = [\n${sensorLines}\n];\n\nexport const SENSOR_GROUPS: SensorGroupDefinition[] = [\n${groupLines}\n];\n`;

const targetPath = path.resolve(__dirname, '../src/data/sensors.ts');
fs.writeFileSync(targetPath, output);
console.log('Wrote', sensorEntries.length, 'sensors to data module');
